/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_demo_jnidemo_FooCDiaoJava */

#ifndef _Included_com_example_demo_jnidemo_FooCDiaoJava
#define _Included_com_example_demo_jnidemo_FooCDiaoJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_demo_jnidemo_FooCDiaoJava
 * Method:    cDiaojavaJingTai
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_demo_jnidemo_FooCDiaoJava_cDiaojavaJingTai
  (JNIEnv *, jobject);

/*
 * Class:     com_example_demo_jnidemo_FooCDiaoJava
 * Method:    javaDiaoC1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_demo_jnidemo_FooCDiaoJava_javaDiaoC1
  (JNIEnv *, jobject);

/*
 * Class:     com_example_demo_jnidemo_FooCDiaoJava
 * Method:    javaDiaoC2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_demo_jnidemo_FooCDiaoJava_javaDiaoC2
  (JNIEnv *, jobject);

/*
 * Class:     com_example_demo_jnidemo_FooCDiaoJava
 * Method:    javaDiaoC3
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_demo_jnidemo_FooCDiaoJava_javaDiaoC3
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
