/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_demo_jnidemo_Foo */

#ifndef _Included_com_example_demo_jnidemo_Foo
#define _Included_com_example_demo_jnidemo_Foo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_demo_jnidemo_Foo
 * Method:    foo1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_demo_jnidemo_Foo_foo1
  (JNIEnv *, jobject);

/*
 * Class:     com_example_demo_jnidemo_Foo
 * Method:    foo2
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_demo_jnidemo_Foo_foo2
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_example_demo_jnidemo_Foo
 * Method:    get_String
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_demo_jnidemo_Foo_get_1String
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
